{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.secname  }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $.Files.Get "virtusnoob.duongaxq.online/cert.pem"  | b64enc }}
  tls.key: {{ $.Files.Get "virtusnoob.duongaxq.online/privkey.pem"  | b64enc }}
{{- end }}
