# values.yaml
replicaCount: 2

image:
  repository: registry.gitlab.com/tgpham26/pnhappproject
  pullPolicy: Always
  tag: v5.0
  #repository: docker.io/trourest186/nodejsmysql
  #tag: latest

imagePullSecrets:
  - name: registry-pnh-secret

db:
  host: 10.0.4.229
  user: root
  pass: "1"

    #nodejs:
    #  - name: MYSQL_HOST
    #  value: "mysql.dev.svc.cluster.local"
    #  - name: MYSQL_PORT
    # value: "3306"
    # - name: MYSQL_USER
    # value: "root"
    #  - name: MYSQL_PASSWORD
    # value: "test1234"
    # - name: MYSQL_DATABASE
    #   value: "nodejsdb"
database:
  db_host: "mysql.dev.svc.cluster.local"
  db_user: "root"
  db_pass: "test1234"
  db_port: "3306"
  db_database: "nodejsdb"

service:
  name: nodejs
  type: NodePort
  port: 8080
  nodePort: 31000

deployment:
  name: nodejs

# Deploy token
# values.yaml
#secret:
  #  name: registry-pnh-secret-trourest
    #  namespace: dev
    #  dockerServer: registry.gitlab.com
    #  dockerUsername: gitlab+deploy-token-3538325
    #  dockerPassword: G7yWrz4jHD4oTfy9zSRc
    #  dockerEmail: tgpham26@gmail.com
imagePullSecrets: [{"name": "registry-pnh-secret"}]

imageCredentials:
  registry: registry.gitlab.com/tgpham26/pnhappproject
  username: gitlab+deploy-token-3538325
  password: G7yWrz4jHD4oTfy9zSRc 
  email: tgpham26@gmail.com

namespace: dev

# Ingress
# values.yaml
ingress:
  secname: secretdns
  enabled: true
  name: python-ingress
  namespace: dev
  className: nginx
  host: www.trourest186.online
  path: /
  serviceName: nodejs
  servicePort: 8080
  tls:
    - secretName: secretdns
      hosts:
        - www.trourest186.online

