apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          env:
            {{- range .Values.nodejs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}

